name: Camply Campsite Watcher
slug: camply
version: "1.0.0"
description: Run Camply 24/7 and notify Home Assistant when campsites open
startup: services
boot: auto

arch:
  - aarch64
  - amd64

build: .
